### ISSUE TITLE
Release notes should be updated for every release.

### ISSUE THREAD

**Issue by dsully** [psf/cachecontrol#133]
The current release notes are 2 years old. It's hard to keep track of what has changed by reading through commit logs.

Thanks

**Comment by ionrock** [comment]
@dsully This is a good point an while I'd like to automate the process based on commit message to improve the release notes (at least keeping them current) I'm doubtful I will spend the time to do so. Would it be better in your opinion to simply remove them?

**Comment by dsully** [comment]
I think the current one isn't useful as it stands. Something like this: http://releases.readthedocs.io/en/latest/ might help automate.

**Comment by anarcat** [comment]
i think this can be closed.

**Comment by woodruffw** [comment]
#249.
