### ISSUE TITLE
Feature request: auto import subpackages or modules

### ISSUE THREAD

**Issue by cryptogun** [psf/cachecontrol#188]
`AttributeError: module 'cachecontrol' has no attribute 'caches'`
```python
cachecontrol.caches.FileCache()
```
Solution from [SO](https://stackoverflow.com/questions/4871369/python-error-attributeerror-module-object-has-no-attribute) is to auto import subs into main `__init__.py`
Thanks.

**Comment by woodruffw** [comment]
Thanks for filing this! 

I'm tempted to punt on this for now: having re-exports through the top-level is often convenient, but increases maintenance complexity (more ways to accidentally break a public import by moving things around). Plus, it makes accidental circular imports easier, and makes it harder for us to perform global searches of GitHub for common import patterns (which helps determine safe/reasonable deprecation periods).
