### ISSUE TITLE
HEAD clobbers GET cache

### ISSUE THREAD

**Issue by jayvdb** [psf/cachecontrol#216]
Mixing HEAD and GET requests for the same URL does not work.  This isnt enabled by default, but afaics any use of the `cacheable_methods` to be anything other than `GET` will problematic.

This is a similar problem to POST https://github.com/ionrock/cachecontrol/issues/211 , and it is also solved in requests-cache because it uses a key which includes the `method`.

At the moment, `invalidating_methods` should include `PATCH` and `POST`.  The former definitely invalidates the cache, and a POST to a URL are very likely to mean a cached value for `GET` of that URL will be outdated.

**Comment by woodruffw** [comment]
Looks like `PATCH` was added with https://github.com/psf/cachecontrol/pull/221, so I think the current `invalidating_methods` set is now (more) complete.

Someone raised a similar problem in #337, and I've come to a similar conclusion as you: setting `cacheable_methods` to anything besides `GET` is almost certainly going to result in incorrect or at least subtly spec-violating responses.

**Comment by woodruffw** [comment]
Per last comment, the invalidation bit of this is addressed with #211 and the `cacheable_methods` part is under discussion in #337, so I'll close this out in favor of the newer issue 🙂
