### ISSUE TITLE
Please pin the version range of msgpack to avoid future breakage

### ISSUE THREAD

**Issue by dbaxa** [psf/cachecontrol#217]
Please pin the version range of `msgpack` to not exceed say version 2.0.0, in order to help mitigate breaking changes in `msgpack` affecting downstream users of `CacheControl`.

**Comment by woodruffw** [comment]
Hi @dbaxa! Sorry for the late response here.

This seems like a good idea to me, although we'll probably need to give some thought to how to we want to introduce this constraint. That being said, pinning to `< 2.0.0` seems reasonable.

@frostming any objections? If not, I'll make a PR for this.
