### ISSUE TITLE
No handlers could be found for logger "cachecontrol.controller"

### ISSUE THREAD

**Issue by dvershinin** [psf/cachecontrol#230]
Using the latest CacheControl and Python 2.7.

When I was using `logging.basicConfig` in my code, I was rarely getting the Cache Deserialization warning.

Now, once `logging.basicConfig` was removed, I am sometimes getting:

> No handlers could be found for logger "cachecontrol.controller"

It appears that this is caused by the same deserialization warning, and the logger had no handlers attached.

Indeed, CacheControl's `setup_logging()` is [only invoked for CLI tool](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/_cmd.py#L19).

I think there should be [opt-in behavior for logging](https://realpython.com/python-logging-source-code/#library-vs-application-logging-what-is-nullhandler).

**Comment by dvershinin** [comment]
The result should be that whoever previously used `logging.basicConfig` in their own code will still get the warning when it's valid.
Whoever did not opt for any logging (did not use `logging.basicConfig` in their own code) will not get the warning.

**Comment by hexagonrecursion** [comment]
Why was this left open?

**Comment by dvershinin** [comment]
I think it is safe to close when >= v0.12.7 is tagged.
