### ISSUE TITLE
PEP 440

### ISSUE THREAD

**Issue by 0xbentang** [psf/cachecontrol#261]
In setup.py we have

`python_requires=">=3.6.*"`

Which is not compatible with PEP440

```
>>> import pep440
>>> from pep440 import is_canonical
>>> is_canonical('3.6.5')
True
>>> is_canonical('3.6.*')
False
```

I am using Poetry and this completely breaks the functionality of Poetry.

Similar issue:

https://github.com/adrienverge/yamllint/issues/387

**Comment by ionrock** [comment]
Done! 

https://pypi.org/project/CacheControl/0.12.8/

**Comment by martinxsliu** [comment]
Thank you @ionrock !
