### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by itamarst** [psf/cachecontrol#278]
Thanks for merging #277. Can we get a release with that, since `pip` prefers to vendor released versions? Thank you!

**Comment by itamarst** [comment]
Just checking—might you have time for this? Thank you!

**Comment by itamarst** [comment]
Hi—if you have a little time, this would be useful.

**Comment by woodruffw** [comment]
See #300: we've been able to add some additional maintainers to this project, so we should be able to create a new release soon!

**Comment by frostming** [comment]
Hi, https://pypi.org/project/CacheControl/0.13.0/ has been released.
