### ISSUE TITLE
cachecontrol uses the deprecated utcnow method

### ISSUE THREAD

**Issue by pfmoore** [psf/cachecontrol#291]
There are two places ([here](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/heuristics.py#L16) and [here](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/caches/redis_cache.py#L23)) in the codebase that use [datetime.utcnow](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow).

This will start raising deprecation warnings in Python 3.12.

**Comment by frostming** [comment]
Closed by #290
