### ISSUE TITLE
Re-homing + new maintainers

### ISSUE THREAD

**Issue by woodruffw** [psf/cachecontrol#300]
Given the lack of maintainer activity and growing issues (xrefs below), I think it might be time to consider a (soft) fork of this project.

I'm willing to temporarily maintain such a fork, at least until the maintainer becomes available again (or expresses a disinterest in continuing to maintain, at which point it'll become a hard fork). My maintenance interest is primarily as a downstream user of `CacheControl`, namely in [`pypa/pip-audit`](https://github.com/pypa/pip-audit).

I'm opening this issue to gauge interest/appetite for such a fork.

xrefs:

* #292
* #293 
* #295 
* #297 
* #298 
* #299

**Comment by woodruffw** [comment]
Oh, fantastic! 

Yes, I'd be happy to collaborate on it -- I started some changes on https://github.com/woodruffw-forks/cachecontrol/tree/modernize (including cherry-picking your double-read fix), but it looks like you've already got most of the same ones covered 🙂 

I haven't used PDM before, but I'm happy to try.

**Comment by frostming** [comment]
Good, I've sent the invitation and I will complete the dev guide shortly.

**Comment by adiroiban** [comment]
Rather than moving to a fork that is maintained again by a single person, I guess it's much better to find an umbrella organization to host the package.

I remember that @ionrock was active in the #294  PR.

I think that instead of links to issues, is best to provide links to PRs that are in great shape and ready to merge, but not merged because @ionrock didn't had time to approve them.

In the case of #294 the PR description is `fix: compatibility with urllib3 2.0` but it contains unrelated formatting changes and unrelated import reordering changes.

**Comment by Secrus** [comment]
Moving the repo to an org won't automatically solve the problem of a lack of maintainers. I'd say that the project could be left as it is, you just need people interested in helping with maintenance.

**Comment by woodruffw** [comment]
I think neither of those is salient in this case: the current maintainer has expressed a willingness to re-home it under an org, and there are at least two people in this thread who are willing to maintain it (myself and @frostming).

**Comment by ewdurbin** [comment]
PSF will happily accept a transfer and manage access!

**Comment by woodruffw** [comment]
> PSF will happily accept a transfer and manage access!

Awesome! I think @ionrock will have to coordinate it if it's done as a transfer; from there, myself or @frostming (or anyone else who'd like to offer maintenance) can be added.

**Comment by Secrus** [comment]
> I think neither of those is salient in this case: the current maintainer has expressed a willingness to re-home it under an org, and there are at least two people in this thread who are willing to maintain it (myself and @frostming).

Yeah, I just meant that is about people, not the org the repo is under.



> > PSF will happily accept a transfer and manage access!
> 
> Awesome! I think @ionrock will have to coordinate it if it's done as a transfer; from there, myself or @frostming (or anyone else who'd like to offer maintenance) can be added.

I will be happy to help with maintenance as well.

**Comment by ewdurbin** [comment]
@ionrock from https://github.com/ionrock/cachecontrol/transfer, you can invite to transfer to https://github.com/psf/ by typing `psf` in the field "Specify an organization or username"

<img width="306" alt="psf" src="https://github.com/ionrock/cachecontrol/assets/1200832/405ba95a-ee78-4f90-aa0c-35a2f1e4c9e0">

I will then accept transfer, create a team comprised of @woodruffw and @frostming in the psf org and assign them admin on the repo.

Outstanding questions:
  - Would you like to remain as a maintainer in any capacity?
  - Will you grant Owner privileges on the project on PyPI to the new maintainers?

**Comment by frostming** [comment]
@ionrock what is the progress of the transfer? I has become a collaborator but still don't have the access to PyPI. Alternatively, you can setup a [Trusted Publisher](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) for GitHub Actions, so that I can setup an automated release workflow later.

**Comment by ionrock** [comment]
@ewdurbin I'm OK being a maintainer, although I doubt I'd spend much time on it (obviously!). 

We can also grant privileges to PyPI. I'm sending the transfer request now.

**Comment by ewdurbin** [comment]
grrr, forgot about that roadblock. @ionrock if you grant me temporary admin access to this repo, I can initiate the transfer.

**Comment by ionrock** [comment]
@ewdurbin I can't seem to find anything that allows making someone else an admin. Any ideas why that could be the case?

**Comment by ewdurbin** [comment]
I thought that there would be a "Role" drop down for each collaborator at https://github.com/ionrock/cachecontrol/settings/access

**Comment by ionrock** [comment]
Unfortunately, there isn't @ewdurbin. I could be missing something, but I've been looking for a while now and don't see any roles I can set for collaborators.

**Comment by woodruffw** [comment]
@ionrock would you be able to take a screencap of what you see on that page?

Here's what I see on another repository I control:

<img width="842" alt="Screenshot 2023-05-30 at 5 34 22 PM" src="https://github.com/ionrock/cachecontrol/assets/3059210/1f1635ed-c5b9-4d22-b2c7-5fe5d96dad38">

(Note the little drop-downs on the right that show the current role.)

**Comment by ionrock** [comment]
<img width="787" alt="Screenshot 2023-05-30 at 4 48 55 PM" src="https://github.com/ionrock/cachecontrol/assets/509830/6df9556a-7a2e-4526-af45-37086526ec63">

@ewdurbin Here you go!

**Comment by ionrock** [comment]
Ah hah! I need to create an org I think https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository#about-access-management-for-repositories

**Comment by ewdurbin** [comment]
🎉 awesome! it’s been moved.

@ionrock @woodruffw @frostming, please accept the org invite and I’ll finalize GitHub permissions.

**Comment by frostming** [comment]
Thanks @ionrock @ewdurbin 🎉  

> We can also grant privileges to PyPI. I'm sending the transfer request now.

But I didn't receive that.

**Comment by woodruffw** [comment]
Accepted, thanks @ewdurbin and @ionrock!

Duping what @frostming said: I also haven't received the PyPI transfer yet 🙂

**Comment by ionrock** [comment]
@ewdurbin is there a recommendation for how best to enable pypi access? I can add individual users, but I suspect adding an org or something similar would be best over time.

**Comment by ewdurbin** [comment]
Orgs would be cool! https://pypi.org/org/psf/ exists, and could home it.

You can add my user `ewdurbin` as owner on PyPI and I will happily organize things equivalent to how it has been organized on GitHub.

**Comment by ewdurbin** [comment]
Just for transparency (lightly redacted to not dox @ionrock)
<img width="808" alt="history" src="https://github.com/psf/cachecontrol/assets/1200832/b0b3b43d-b16b-4f1a-b1d7-3a862bec182a">

**Comment by woodruffw** [comment]
Received! I think that completes all transfers, so this should be safe to close.

Any objections @ionrock @ewdurbin @frostming?

**Comment by woodruffw** [comment]
Cool, closing!

**Comment by frostming** [comment]
@ewdurbin Hi, is there a good place for the maintainers instant messaging? Is the Python Slack channel still recommended?

**Comment by ewdurbin** [comment]
I'm on PSF Slack, and I know @woodruffw is as well. @ionrock would of course be welcome.

Though I'm also adaptable.

**Comment by frostming** [comment]
> I'm on PSF Slack, and I know @woodruffw is as well. @ionrock would of course be welcome.
> 
> Though I'm also adaptable.

Good to know that, can you provide the link to it?
