### ISSUE TITLE
Trusted publishing to PyPI

### ISSUE THREAD

**Issue by woodruffw** [psf/cachecontrol#306]
We can use PyPI's new trusted publishing support to publish directly from GitHub Actions without a manual API token: https://docs.pypi.org/trusted-publishers/using-a-publisher/

**Comment by frostming** [comment]
Yeah, but we still can't set up an automated release workflow. We'll need to manually upload for this time.

@ionrock Trusted publishers is still worth doing.

**Comment by woodruffw** [comment]
> Yeah, but we still can't set up an automated release workflow. We'll need to manually upload for this time.

I might be misunderstanding, but why not? Trusted publishing shouldn't require any secret configuration, so all we should need is commit access to the repo and management on the PyPI project.

**Comment by frostming** [comment]
@woodruffw Sorry for the misunderstand, I mean we still can't set up automated release workflow under the current situation.

**Comment by woodruffw** [comment]
All good! Just making sure I understood as well. I can try and get the trusted publisher set up in a little bit.

**Comment by woodruffw** [comment]
Success: https://pypi.org/project/CacheControl/0.13.1rc0/

Run: https://github.com/psf/cachecontrol/actions/runs/5207394556
