### ISSUE TITLE
Dependency change in patch version `0.12.13` broke some projects

### ISSUE THREAD

**Issue by stilllman** [psf/cachecontrol#311]
Release `0.12.13` as the same problem as described [#286](https://github.com/psf/cachecontrol/issues/286) which ended up with `0.12.12` being yanked: it changed the `lockfile` dependency to `filelock`, possibly breaking projects that pulled `lockfile` themselves instead of using `CacheControl[filecache]`.

**Comment by stilllman** [comment]
Wow that was fast, thank you!

**Comment by woodruffw** [comment]
@stilllman any other remaining issues here? If not, I'll close this out 🙂

**Comment by stilllman** [comment]
From what I can see the problem is fixed with the new release, thank you for the amazingly swift update!
