### ISSUE TITLE
Race condition in FileCache that can result in empty body 200 response

### ISSUE THREAD

**Issue by thatch** [psf/cachecontrol#332]
I don't have a test case or suggested fix (yet), but documenting that this exists:

1. Poetry (unlike pip) uses cachecontrol's `FileCache` with no modifications.
2. If there is already a cached response, and two different processes (or threads too, probably) revalidate at the same time getting a 304, the first one goes through [`_cache_set`](https://github.com/psf/cachecontrol/blob/0e091c6524fae758b6c422a9e1aa16f99483e65c/cachecontrol/controller.py#L496-L497) and the second one can [find no body](https://github.com/psf/cachecontrol/blob/0e091c6524fae758b6c422a9e1aa16f99483e65c/cachecontrol/controller.py#L470-L474) (returning a response with empty body because `_secure_open_write` [deletes before creating](https://github.com/psf/cachecontrol/blob/0e091c6524fae758b6c422a9e1aa16f99483e65c/cachecontrol/caches/file_cache.py#L39-L52)).

Potential ideas:
* Check [for None body](https://github.com/psf/cachecontrol/blob/0e091c6524fae758b6c422a9e1aa16f99483e65c/cachecontrol/controller.py#L152-L155), and try harder (maybe `.get(locked=True)`.  Pro: simple, targeted change that only affects the rare case, Con: api change, deletion can still race
* Protect get (and delete) with the same lock that set uses, every time.  Pro: simple, Con: performance, race can still return mismatched body (similar to #324 with `SeparateBodyFileCache`)
* Stop using bespoke `mkstemp` that has a race, use `os.replace`.  Pro: less code, file isn't missing during the set, Con: commit history doesn't make it obvious why this exists, seems defensive against problems in world-writable cache dirs or maybe a windows issue?

**Comment by woodruffw** [comment]
> * Stop using bespoke `mkstemp` that has a race, use `os.replace`.  Pro: less code, file isn't missing during the set, Con: commit history doesn't make it obvious why this exists, seems defensive against problems in world-writable cache dirs or maybe a windows issue?

This seems like a clean approach to me. I don't have any additional insight to add on why we don't already use `os.replace`, except that it might be because `os.replace` wasn't added until 3.3 and the older `os.rename` doesn't have the same consistent POSIX-esque semantics on Windows (whereas `os.replace` does).
